create table network(
appname varchar(50),
apppackage varchar(200),
appver varchar(100),
city varchar(300),
clientip varchar(200),
county varchar(200),
dataquality int,
datetime int,
devicebrand varchar(200),
devicefactory varchar(200),
deviceid string,
devicename varchar(200),
dnstime int,
firsttime int,
network varchar(50),
operator varchar(100),
os varchar(50),
osversion varchar(50),
region varchar(50),
reqtype varchar(50),
rescode varchar(50),
reserror varchar(1000),
resolution varchar(100),
restime int,
sdkversion varchar(100),
serverip varchar(100),
ssltime int,
sysversion varchar(200),
tcptime int,
time varchar(200),
url varchar(200),
year varchar(50),
month varchar(50),
day varchar(50),
hour varchar(50)
)
insert into table network
SELECT 
get_json_object(origianl_json_table.jsonContent, '$.appname') as appname,
get_json_object(origianl_json_table.jsonContent, '$.apppackage') as apppackage,
get_json_object(origianl_json_table.jsonContent, '$.appver') as appver,
get_json_object(origianl_json_table.jsonContent, '$.city') as city,
get_json_object(origianl_json_table.jsonContent, '$.clientip') as clientip,
get_json_object(origianl_json_table.jsonContent, '$.county') as county,
get_json_object(origianl_json_table.jsonContent, '$.dataquality') as dataquality,
get_json_object(origianl_json_table.jsonContent, '$.datetime') as datetime,
get_json_object(origianl_json_table.jsonContent, '$.devicebrand') as devicebrand,
get_json_object(origianl_json_table.jsonContent, '$.devicefactory') as devicefactory,
get_json_object(origianl_json_table.jsonContent, '$.deviceid') as deviceid,
get_json_object(origianl_json_table.jsonContent, '$.devicename') as devicename,
get_json_object(origianl_json_table.jsonContent, '$.dnstime') as dnstime,
get_json_object(origianl_json_table.jsonContent, '$.firsttime') as firsttime,
get_json_object(origianl_json_table.jsonContent, '$.network') as network,
get_json_object(origianl_json_table.jsonContent, '$.operator') as operator,
get_json_object(origianl_json_table.jsonContent, '$.os') as os,
get_json_object(origianl_json_table.jsonContent, '$.osversion') as osversion,
get_json_object(origianl_json_table.jsonContent, '$.region') as region,
get_json_object(origianl_json_table.jsonContent, '$.reqtype') as reqtype,
get_json_object(origianl_json_table.jsonContent, '$.rescode') as rescode,
get_json_object(origianl_json_table.jsonContent, '$.reserror') as reserror,
get_json_object(origianl_json_table.jsonContent, '$.resolution') as resolution,
get_json_object(origianl_json_table.jsonContent, '$.restime') as restime,
get_json_object(origianl_json_table.jsonContent, '$.sdkversion') as sdkversion,
get_json_object(origianl_json_table.jsonContent, '$.serverip') as serverip,
get_json_object(origianl_json_table.jsonContent, '$.ssltime') as ssltime,
get_json_object(origianl_json_table.jsonContent, '$.sysversion') as sysversion,
get_json_object(origianl_json_table.jsonContent, '$.tcptime') as tcptime,
get_json_object(origianl_json_table.jsonContent, '$.time') as time,
get_json_object(origianl_json_table.jsonContent, '$.url') as url,
origianl_json_table.year as year,
origianl_json_table.month as month,
origianl_json_table.day as day,
origianl_json_table.hour as hour
FROM origianl_json_table;


create table usb_device(
deviceid varchar(100),
os varchar(100),
osversion varchar(100),
sysversion varchar(200),
otaversion varchar(200),
devicefactory varchar(100),
devicebrand varchar(100),
devicename varchar(100),
productkey varchar(200),
productid int,
deviceusid string,
devicewifimac varchar(200),
devicebtmac varchar(200),
devicecontrolmac varchar(200),
usbtype varchar(50),
usbfactory varchar(100),
usbproducename varchar(100),
usbname varchar(50),
usbserialnumber varchar(150),
usbstatus varchar(10),
sdkversion varchar(50),
clientip varchar(200),
country varchar(100),
region varchar(100),
city varchar(100),
network varchar(50),
operator varchar(50),
inserttime varchar(200),
time varchar(200),
year varchar(50),
month varchar(50),
day varchar(50),
hour varchar(50)
)
insert into table usb_device
SELECT 
get_json_object(origianl_usb_device.jsonContent, '$.deviceid') as deviceid,
get_json_object(origianl_usb_device.jsonContent, '$.os') as os,
get_json_object(origianl_usb_device.jsonContent, '$.osversion') as osversion,
get_json_object(origianl_usb_device.jsonContent, '$.sysversion') as sysversion,
get_json_object(origianl_usb_device.jsonContent, '$.otaversion') as otaversion,
get_json_object(origianl_usb_device.jsonContent, '$.devicefactory') as devicefactory,
get_json_object(origianl_usb_device.jsonContent, '$.devicebrand') as devicebrand,
get_json_object(origianl_usb_device.jsonContent, '$.devicename') as devicename,
get_json_object(origianl_usb_device.jsonContent, '$.productkey') as productkey,
get_json_object(origianl_usb_device.jsonContent, '$.productid') as productid,
get_json_object(origianl_usb_device.jsonContent, '$.deviceusid') as deviceusid,
get_json_object(origianl_usb_device.jsonContent, '$.devicewifimac') as devicewifimac,
get_json_object(origianl_usb_device.jsonContent, '$.devicebtmac') as devicebtmac,
get_json_object(origianl_usb_device.jsonContent, '$.devicecontrolmac') as devicecontrolmac,
get_json_object(origianl_usb_device.jsonContent, '$.usbtype') as usbtype,
get_json_object(origianl_usb_device.jsonContent, '$.usbfactory') as usbfactory,
get_json_object(origianl_usb_device.jsonContent, '$.usbproducename') as usbproducename,
get_json_object(origianl_usb_device.jsonContent, '$.usbname') as usbname,
get_json_object(origianl_usb_device.jsonContent, '$.usbserialnumber') as usbserialnumber,
get_json_object(origianl_usb_device.jsonContent, '$.usbstatus') as usbstatus,
get_json_object(origianl_usb_device.jsonContent, '$.sdkversion') as sdkversion,
get_json_object(origianl_usb_device.jsonContent, '$.clientip') as clientip,
get_json_object(origianl_usb_device.jsonContent, '$.country') as country,
get_json_object(origianl_usb_device.jsonContent, '$.region') as region,
get_json_object(origianl_usb_device.jsonContent, '$.city') as city,
get_json_object(origianl_usb_device.jsonContent, '$.network') as network,
get_json_object(origianl_usb_device.jsonContent, '$.operator') as operator,
get_json_object(origianl_usb_device.jsonContent, '$.inserttime') as inserttime,
get_json_object(origianl_usb_device.jsonContent, '$.time') as time,
origianl_usb_device.year as year,
origianl_usb_device.month as month,
origianl_usb_device.day as day,
origianl_usb_device.hour as hour
FROM origianl_usb_device;